### ISSUE TITLE
Publishing SSSOM mapping sets should not be a "all-or-nothing" choice

### ISSUE THREAD

**Issue by gouttegd** [INCATools/ontology-development-kit#1035]
The ODK configuration file allows to define mapping set products that can be managed by the ODK:

```
sssom_mappingset_group:
  products:
    - id: my-set
    - id: my-other-set
      mirror_from: ...
```

The section accepts a `release_mappings` boolean parameter (defaulting to `False`) which, when set to `True`, will cause the mapping sets to be treated as “release assets” and published along with the other assets.

AFAICT, it is not possible to ask that only _some_ of the mapping sets defined in that section be treated as release assets. I believe it should be possible to do so. An ontology may need to define several mapping sets, but may only want to publish some of them.

In other words, the `release_mappings` parameter at the level of the `sssom_mappingset_group` should be “overridable” at the level of each individual mapping set product.
