### ISSUE TITLE
Mirroring of a mapping set should honour the `MIR` variable

### ISSUE THREAD

**Issue by gouttegd** [INCATools/ontology-development-kit#1046]
Declaring a SSSOM set in `maintenance` mode as follows:

```yaml
sssom_mappingset_group:
  products:
    - id: fbbt
      maintenance: mirror
      mirror_from: http://purl.obolibrary.org/obo/fbbt/fbbt-mappings.sssom.tsv
```

yields the following code in the generated Makefile:

```Makefile
$(MAPPINGDIR)/fbbt.sssom.tsv:
    wget "http://purl.obolibrary.org/obo/fbbt/fbbt-mappings.sssom.tsv" -O $@
```

in which the mapping set is downloaded unconditionally.

Mirroring a mapping set should obey to the same rules as mirroring an imported ontology. In particular, when `MIR` is set to false, no attempt to download the remote set should be made.
