### ISSUE TITLE
Implementing MIREOT and its custom.Makefile  in ODK Imports

### ISSUE THREAD

**Issue by fathoni** [INCATools/ontology-development-kit#1181]
**Background**
I am working on importing specific terms from the Unit Ontology (UO) as defined in a `uo_terms.txt` file. 

```
UO:0000019  # angstrom
UO:0000063  # nanosecond
UO:0000030  # meter per second
UO:0000150  # millimolar
UO:0000094  # unit of molarity
```

Using ROBOT, I was able to extract these terms and their superclasses with the following command:

```bash
sh run.sh robot extract --method MIREOT \
    --input mirror/uo.owl \
    --lower-term "UO:0000019" \
    --lower-term "UO:0000063" \
    --lower-term "UO:0000030" \
    --lower-term "UO:0000150" \
    --lower-term "UO:0000094" \
    --output extracted_unit.owl
```

This successfully produced the desired `extracted_unit.owl`, which includes the hierarchical structure below:

```
unit
├── length unit
│   └── angstrom based unit
│       └── angstrom
├── concentration unit
│   └── unit of molarity
│       └── molar based unit
│           └── millimolar
├── time unit
│   └── second based unit
│       ├── picosecond
│       └── nanosecond
└── speed/velocity unit
    └── meter per second based unit
        └── meter per second
```

**Goal**
I aim to replicate this process using ODK's config and importing system. To my understanding, this requires a custom `module_type` since MIREOT is not directly supported by ODK's predefined module types.

**Current Attempt**
In my `sample-odk.yaml` configuration file, I added the following:

```yaml
import_group:
  products:
    - id: uo
      module_type: custom
      mirror_from: https://raw.githubusercontent.com/bio-ontology-research-group/unit-ontology/refs/heads/master/uo-full.owl
```

However, I understand that additional modifications are required in the corresponding `sample.Makefile` to handle this custom import. 

**Questions**
1. Is there a pre-requisite, guideline, or example for modifying the `sample.Makefile` to support custom imports e.g., for using MIREOT?
2. What is the recommended approach for implementing custom-based imports in ODK? Should I rely on a `custom` module type, or is there an alternative workflow, possibly using ROBOT *.tsv templates and then modifying the `sample.Makefile` accordingly?

Thank you in advance for your guidance.

**Comment by gouttegd** [comment]
> Is there a pre-requisite, guideline, or example for modifying the sample.Makefile to support custom imports e.g., for using MIREOT?

Not that I am aware of, alas. But the general idea is as follows:

With your current `sample-odk.yaml` configuration (as shown in your message), after seeding your repository the `src/ontology/Makefile` should contain somewhere the following rule:

```Makefile
## Module for ontology: uo

$(IMPORTDIR)/uo_import.owl: $(MIRRORDIR)/uo.owl
        echo "ERROR: You have configured your default module type to be custom; this behaviour needs to be overwritten in sample.Makefile!" && false
```

Now what you need to do is create the `src/ontology/sample.Makefile` (if it does not already exist) and create a rule for the exact same target. In the body of that rule, do whatever you need to create the exact module you want. For example:

```Makefile
$(IMPORTDIR)/uo_import.owl: $(MIRRORDIR)/uo.owl
        $(ROBOT) extract --input $< \
                         --method MIREOT \
                         --lower-term "UO:0000019" \
                         --lower-term "UO:0000063" \
                         --lower-term "UO:0000030" \
                         --lower-term "UO:0000150" \
                         --lower-term "UO:0000094" \
                         --output $@
```

(In case you are not familiar with Makefiles: `$<` represents the first dependency of the rule, in this case `$(MIRRORDIR)/uo.owl` – this the local mirror of the Unit Ontology, that the ODK standard Makefile will have downloaded for you from the mirror location you indicated in the configuration file; `$@` represents the target of the rule, in this case `$(IMPORTDIR)/uo_import.owl` – that’s the module the rule needs to create.)

**Comment by gouttegd** [comment]
@matentzn Why do we have a `tests/test-module-mireot.yaml` test case with

```yaml
import_group:
  products:
    - id: ro
      mirror_from: https://raw.githubusercontent.com/INCATools/ontology-development-kit/master/tests/ontologies/ro.owl
    - id: pato
      mirror_from: https://raw.githubusercontent.com/INCATools/ontology-development-kit/master/tests/ontologies/pato.owl
  module_type: mireot
```

given that `mireot` is _not_ a supported module type?
