### ISSUE TITLE
Module-level `module_type_slme` option should yield a module-specific rule

### ISSUE THREAD

**Issue by gouttegd** [INCATools/ontology-development-kit#1204]
Consider the following `import_group`:

```yaml
import_group:
  module_type: slme
  module_type_slme: TOP
  products:
    - id: ro
    - id: bfo
    - id: pato
      module_type_slme: BOT
```

The intention is clearly that the `ro` and `bfo` modules should be SLME TOP modules, while the `pato` module should be a SLME BOT module. However, the generated Makefile only contains a generic `$(IMPORTDIR)/%_import.owl` rule to produce SLME TOP modules. In other words, the module-level `module_type_slme` option is ignored, and the group-level `module_type_slme` option takes precedence.
