### ISSUE TITLE
Add option to extract a base from mirror

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#290]
in the config of the import, you could be able to say:

```
- id: bqo
   mirror_from: http://purl.org/bqo
   make_base: 
     - http://purl.obolibrary.org/obo/ZP_
     - http://purl.obolibrary.org/obo/ZT_
```

This would than add the ROBOT extract base functionality to the mirror download; basically a workaround for cases where now actual deployed bases are available.

Should use https://github.com/ontodev/robot/pull/570 once it is merged.
