### ISSUE TITLE
Make it possible to pass prefixes.yaml to dosdp-tools?

### ISSUE THREAD

**Issue by srobb1** [INCATools/ontology-development-kit#568]
Hello,

I just updated to ODK 1.3.0. I use dosdp with custom patterns to manage my anatomy ontology. I use foaf_depicted_by. In my most current release I see that I lost these lines in a few different imports and my custom pattern files. Here is a [link to my git diffs](https://github.com/obophenotype/planaria-ontology/compare/v2021-10-21...v2022-03-02#diff-b500706e7527675f543c9e5f98ad88c7e6ae90eefa1accd8903a0e4689fbfe2fR496)

http://purl.obolibrary.org/obo/foaf_depicted_by
http://purl.obolibrary.org/obo/foaf_depiction

![Screen Shot 2022-03-02 at 3 12 21 PM](https://user-images.githubusercontent.com/1072991/156458586-4b3f36fa-52e0-4356-971a-8a6315843888.png)
![Screen Shot 2022-03-02 at 3 11 26 PM](https://user-images.githubusercontent.com/1072991/156458589-0a54e845-d5ca-4154-8128-2e2a91b53cd0.png)
![Screen Shot 2022-03-02 at 3 10 48 PM](https://user-images.githubusercontent.com/1072991/156458593-1573fbbf-e3e7-42d9-8a1d-f8020b941787.png)

I also lost foaf_depicted_by in my custom pattern as well as nested comment properties.

![Screen Shot 2022-03-02 at 3 13 03 PM](https://user-images.githubusercontent.com/1072991/156458580-4649b827-e012-4b08-b220-ae28bb0f28dd.png)

Maybe I just need to change to http://xmlns.com/foaf/0.1/depicted_by

Thanks for any input.

**Comment by matentzn** [comment]
@balhoff does this ring a bell for you? Do you think this is a dosdp tool ticket? Or maybe this is a missing prefix declaration?

**Comment by srobb1** [comment]
I am not sure it would help, but I wanted to try something.

I changed my depicted_by declaration to see if it would help. It did not help at all.

It was:
`http://purl.obolibrary.org/obo/foaf_depicted_by`
and I changed it to:
`http://xmlns.com/foaf/0.1/depicted_by`

All my images annotations are still missing.


Sofia

**Comment by balhoff** [comment]
@srobb1 could you point me to how I could run the needed targets in a checkout of your repo?

**Comment by srobb1** [comment]
Hi @balhoff,

Here is my repo: https://github.com/obophenotype/planaria-ontology

I just run sh ./run.sh make prepare_release

if you look in my `patterns/dosdp-patterns` directory you will see `plana_terms.yaml`. This includes my depicted_by pattern.

In my `data/default/plana.tsv` you will see I  have data for the depicted_by variable:




**defined\_class**|**defined\_class\_name**|**new\_entity**|**new\_entity\_label**|**parent\_entity**|**parent\_entity\_label**|**exact\_syn**|**defined\_class\_definition**|**dbxref**|**def\_dbxref**|**depictedBydepicted\_by**|**image\_comment**|**comment**|**has\_obo\_namespace**|**created\_by**
-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----
PLANA:0002060|nephridiopore|PLANA:0002060|nephridiopore|PLANA:0002079|pore| |The external opening and terminus of a protonephridium made by a terminal cell.|ISBN:9780070316607|PMID:21828097|UBERON:0006972|ISBN:9780070316607|https://raw.githubusercontent.com/obophenotype/planaria-ontology/master/metadata/images/nephridiopore.png|Image is an electron micrograph depicting a collecting duct (arrowheads) passing through the basal lamina (BL). Dorsal is up and the scale bar is 5 um.| |Planarian\_Anatomy|https://orcid.org/0000-0003-2569-1939 | https://orcid.org/0000-0002-7535-4407

**Comment by balhoff** [comment]
This is a problem in dosdp-tools that actually seems to go back a couple of releases. I fixed it and will make a release soon.

**Comment by srobb1** [comment]
Great! Thanks. I guess I have not been using the most up to date dosdp-tools.

**Comment by balhoff** [comment]
@srobb1 when I was debugging this I noticed a few things you might want to change about your pattern YAML:

- The created_by annotation seems to use pipe-separated values but is not set up as a list annotation.
- The values in the `vars` dictionary should be the range of the terms in the input. So for something like `depicted_by` just use `Thing` (define this in your `classes` dictionary as `owl:Thing`).
- Should provide a prefix for `foaf` when you run dosdp-tools.

**Comment by srobb1** [comment]
@balhoff 

Thanks for the input! And thank you for taking the time to review my yaml, this is extremely helpful. It is super great to get my yamls written properly. I have a couple questions.   

_created_by_

I am using lists but not as in my annotations dictionary. I want to make sure I format this properly,


**currently** I have my created_by as:  
```
annotationProperties:
  depicted_by: foaf:depicted_by

vars:
  created_by: "'created_by'"

annotations:
  - annotationProperty: created_by
    text: "%s"
    vars:
      - created_by
```

to change it to a list would it look like this? :
```
annotationProperties:
  depicted_by: foaf:depicted_by

data_list_vars:
  created_by: xsd:string

annotations:
  - annotationProperty: created_by
    value:  created_by
```

__depicted_by__

These are the changes you suggest. Is the formatting okay for everything depicted_by related?
Are my quotes okay in my vars dictionary?

```
classes:
  Thing: owl:Thing

annotationProperties:
  depicted_by: foaf:depicted_by

vars:
  depicted_by: "'Thing'"

annotations:
  - annotationProperty: depicted_by
    var: depicted_by
    annotations:
      - annotationProperty: image_comment
        text: "%s"
        vars:
         - image_comment

```


__foaf prefix__

I run ODK prepare_release, how do I provide a prefix for `foaf` when I run dosdp-tool from within ODK? I have it in my plana-edit.owl `Prefix(foaf:=<http://xmlns.com/foaf/0.1/>)`. Is there somewhere else I need to put it or some other way to handle this?

Thank you again,
Sofia
