### ISSUE TITLE
error when importing dcterms

### ISSUE THREAD

**Issue by wdduncan** [INCATools/ontology-development-kit#614]
I am wanting to use the `dcterms` library directly in an ontology like so:
```
import_group:
  products:
  - id: dcterms
      mirror_from: http://protege.stanford.edu/plugins/owl/dc/terms.owl
```
When running `seed-via-docker.sh -C configs/foo-odk.yaml` I get the error:
```
ERROR OWLOntologyManagerImpl.checkForOntologyIDChange() new:Ontology(OntologyID(Anonymous-15)) [Axioms: 0 Logical Axioms: 0] First 20 axioms: {}
Could not load imported ontology: <http://protege.stanford.edu/plugins/owl/dc/terms.owl> Cause: Ontology already exists. OntologyID(OntologyIRI(<http://purl.org/dc/terms/>) VersionIRI(<null>))
```
ODK yaml file attached.
[foo-odk.yaml.txt](https://github.com/INCATools/ontology-development-kit/files/8909522/foo-odk.yaml.txt)

**Comment by matentzn** [comment]
@wdduncan 

@anitacaron and I looked into the issue, this is a deeply buried issue in ROBOT, not ODK. Probably very complex to solve. However, there is an easy workaround: you can declare it as "large":

```
import_group:
  products:
    - id: bfo
      module_type: mirror
      mirror_from: http://purl.obolibrary.org/obo/bfo/2020/bfo.owl
    - id: dcterms
      mirror_from: http://protege.stanford.edu/plugins/owl/dc/terms.owl
      is_large: TRUE
```

This  way, ODK does not try to process the metadata in terms.owl, and it all works ok. This problem wont fix, but I hope the workaround is good enough. Sorry about that! If you want, you can make a ROBOT issue, this is how you can reproduce the ERROR:

```
echo "INSERT DATA { <A> <B> <C> }" > q.sparql 
robot query -I http://protege.stanford.edu/plugins/owl/dc/terms.owl --update q.sparql merge -o tmp/test.ofn
```
