### ISSUE TITLE
Migrating SWO build into ODK

### ISSUE THREAD

**Issue by allysonlister** [INCATools/ontology-development-kit#679]
I've successfully created an empty SWO repo via ODK, but now need to think carefully about how to integrate my existing SWO ontology file and any relevant accompanying documentation into my existing repo at https://github.com/allysonlister/swo

As https://oboacademy.github.io/obook/tutorial/migrating-ontology-to-odk/ is empty, please could someone provide some pointers?

I have the following vague ideas:

1. create a branch (e.g. upgrade-to-odk) in my existing repo and work in that
2. copy everything I need from upgrade-to-odk (primarily my owl files) into the new odk structure I've created
3. do some kind of massive git copy or move or something from the new odk structure I have to the upgrade-to-odk branch.

Of course it's not that simple. I currently import the terms we need from external ontologies using Ontofox (here is our [config file](https://github.com/allysonlister/swo/blob/master/dev/ontology/swo-ontofox-annotation.txt) for that). I realise that the ODK uses [SLME from robot](http://robot.obolibrary.org/extract#syntactic-locality-module-extractor-slme) in some way to pull terms, but I'm not sure how to configure that. There are only a very few terms, so I'm hopeful this will be straightforward once I know how to do it :-)

I've had some interest in the community to help me update SWO, and getting this ODK version up and running would be a huge step to allowing others to successfully create PRs etc as the current make and build system is a bit outdated.

Just getting an initial version of the ODK repo integrated within my existing repo would be great - tweaks and bells and whistles (git actions, continuous integration etc) are for the future I think...

Do you have any tips please?

This is my current project yaml that I've built the empty ODK repo with:

```yaml
id: swo
title: Software Ontology
github_org: allysonlister
repo: swo
import_group:
  products:
    - id: bfo
    - id: obi
edit_format: owl
release_artefacts: 
  - base
  - full
  - non-classified
export_formats:
  - owl
  - obo
  - json
namespaces: 
  - http://www.ebi.ac.uk/swo/SWO_
license: CC-BY 4.0
```

Thanks!
