### ISSUE TITLE
Adding templates to ODK builds

### ISSUE THREAD

**Issue by allysonlister** [INCATools/ontology-development-kit#695]
As described on Slack, I would like to create my t4fs-edit.owl file using templates, so I won't actually be editing t4fs-edit.owl at all - all edits will be made in the templates and then propagated through the ODK workflow. @matentzn suggested that I put questions in here, as this process is not yet documented.

Nico had this to say to help me with the process, for reference:

> For the ROBOT template driven management, you only add a component, which you can automatically connect to templates: https://gitlab.c-path.org/c-pathontology/critical-path-ontology/-/blob/main/src/ontology/cpont-odk.yaml#L64 

Questions:

1. can I put `t4fs-edit.owl` as the value for `filename` below? That would be best, and show clearly that `t4fs-edit.owl` is a generated file. Would it cause any issues for the build process?
2. How do I chain this with an `annotate` to the template command, so that I can add a licence, description, comment and title to the ontology itself?
3. How do I ensure that the resulting output is in ofn format, even if the filename remains `.owl` so as not to confuse the generated makefile? ofn seems a lot easier for diffs etc. I know robot has a diff feature, but it would be great to be able to use ofn please.
4. I currently have my templates in src/ontology/templates/ - where does the ODK expect them, as it isn't clear from the example yaml file? 

Here's what I have so far added to my yaml file:
```yaml
components:
  products:
    - filename: t4fs-template.owl
      use_template: TRUE
      template_options: --add-prefixes config/context.json
      templates:
        - index.tsv
        - properties.tsv
        - t4fs.tsv
```

Thanks!
