### ISSUE TITLE
Import behaviour change after ODK upgrade

### ISSUE THREAD

**Issue by hkir-dev** [INCATools/ontology-development-kit#780]
I have an ODK project in a private repo (due to private collaborator data). Upgraded this project from ODK v1.2.32 to v1.3.2-dev.

Now I observe that `imports/*_import.owl` files are not generated any more. However, I can still see the related rules (`$(IMPORTDIR)/%_import.owl:`) in the Makefile.

The major differences between two version I can observe are these lines:

Makefile v1.2.32
```Makefile
IMPORTS =  pr go ro uberon pato cl ensmusg ncbitaxon

IMPORT_ROOTS = $(patsubst %, imports/%_import, $(IMPORTS))
IMPORT_OWL_FILES = $(foreach n,$(IMPORT_ROOTS), $(n).owl)
IMPORT_FILES = $(IMPORT_OWL_FILES)
```

Makefile v1.3.2-dev
```Makefile
IMPORTS =  pr go ro uberon pato cl ensmusg ncbitaxon

IMPORT_ROOTS =  $(IMPORTDIR)/merged_import
IMPORT_OWL_FILES = $(foreach n,$(IMPORT_ROOTS), $(n).owl)
IMPORT_FILES = $(IMPORT_OWL_FILES)
```

Is this an expected behavior? This import issue is not affecting the output ontology, just asking to ensure migration is OK.

**Comment by matentzn** [comment]
Can you paste the content of your `ont-odk.yaml` file?

**Comment by hkir-dev** [comment]
```yaml
id: bdso
title: Brain Data Standards Cell Ontology
github_org: obophenotype
repo: bdso
use_dosdps: TRUE
export_formats:
  - owl
  - obo
  - json
release_artefacts:
  - base
  - simple-non-classified
  - full
  - simple
primary_release: full
import_group:
  use_base_merging: TRUE
  slme_individuals: exclude
  exclude_iri_patterns:
    - <http://www.informatics.jax.org/marker/MGI:*>
    - <http://purl.obolibrary.org/obo/OBA_*>
    - <http://purl.obolibrary.org/obo/ENVO_*>
    - <http://purl.obolibrary.org/obo/OBI_*>
    - <http://purl.obolibrary.org/obo/GOCHE_*>
    - <http://purl.obolibrary.org/obo/CARO_*>
    - <http://purl.obolibrary.org/obo/NCBITaxon_Union_*>
    - <http://www.genenames.org/cgi-bin/gene_symbol_report*>
  products:
    - id: pr
      make_base: TRUE
      mirror_from: https://raw.githubusercontent.com/obophenotype/pro_obo_slim/master/pr_slim.owl
      is_large: TRUE
    - id: go
      use_base: TRUE
      base_iris:
        - http://purl.obolibrary.org/obo/GO_
        - http://purl.obolibrary.org/obo/GOREL_
        - http://purl.obolibrary.org/obo/GOCHE_
    - id: ro
      use_base: TRUE
    - id: uberon 
      use_base: TRUE
    - id: pato
      use_base: TRUE
    - id: cl
      use_base: TRUE
    - id: ensmusg
      make_base: TRUE
    - id: ncbitaxon
      mirror_from: http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim.owl
components:
  products:
    - filename: all_templates.owl
```
