### ISSUE TITLE
Makefile: module_type: filter does not work in a specific case

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#813]
```
import_group:
  module_type: filter
  products:
   - id: orcidio
      module_type: filter
      mirror_from: https://w3id.org/orcidio/orcidio.owl
      annotation_properties:
        - rdfs:label
        - http://purl.org/dc/elements/1.1/description
        - http://purl.org/dc/elements/1.1/source
      base_iris:
        - https://orcid.org/
```

Somehow, this results in orcidio becoming SLME module
