### ISSUE TITLE
slme_individuals: exclude keeps individuals in imports

### ISSUE THREAD

**Issue by pfabry** [INCATools/ontology-development-kit#854]
This issue is a follow-up of #849 

I tried to filter out individuals  in *-odk.yaml:
```
import_group:
    products:
    - id: bfo
    - id: omo
      module_type: slme (I believe that this line is unnecessary)
      slme_individuals: exclude
```

Update_repo created the following command in the makefile:

```
## Module for ontology: omo

$(IMPORTDIR)/omo_import.owl: $(MIRRORDIR)/omo.owl $(IMPORTDIR)/omo_terms_combined.txt
	if [ $(IMP) = true ]; then $(ROBOT) query -i $< --update ../sparql/preprocess-module.ru \
		extract -T $(IMPORTDIR)/omo_terms_combined.txt --copy-ontology-annotations true --force true --individuals exclude --method BOT \
		query --update ../sparql/inject-subset-declaration.ru --update ../sparql/inject-synonymtype-declaration.ru --update ../sparql/postprocess-module.ru \
		$(ANNOTATE_CONVERT_FILE); fi
```

Yet, the resulting omo_import.owl still includes all individuals from mirrored OMO. 

example: https://github.com/pfabry/ODKTestImports/pull/5

edit: running directly the ROBOT command extract with --individuals exclude also keeps the individuals:
`robot extract --method BOT --input omo_import.owl --term-file omo_terms_combined.txt --individuals exclude --output omo_test.owl`
